language: objective-c
osx_image: xcode10.2

script:
  - xcodebuild -project Project/Project.xcodeproj -scheme Fluorine -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build
